### ISSUE TITLE
naming 이슈

### ISSUE THREAD

**Issue by gschoe** [sogang-mm/AnalysisModule#7]
* 다른 모듈들의 기본이 되므로 _base 형태의 naming이 필요할 것 같음.
* fork한 모듈들의 repo name을 변경해서 fork 하는 것을 고려할 필요가 있음.
  * fork된 모듈들이 하나의 시스템으로 packaging 되는 것을 고려할 필요가 있음.

**Comment by kepler92** [comment]
장기 과제로 남겨주고 issue close
